//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albumes_MemoriesByCoco.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MemoriesByCocoEntities : DbContext
    {
        public MemoriesByCocoEntities()
            : base("name=MemoriesByCocoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PA_INS_RegistrarUsuario(string strNombre, string strApellido1, string strApellido2, string strCorreo, string strTelefono, string strDireccion, string strUsuario, string strPass)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strApellido1Parameter = strApellido1 != null ?
                new ObjectParameter("strApellido1", strApellido1) :
                new ObjectParameter("strApellido1", typeof(string));
    
            var strApellido2Parameter = strApellido2 != null ?
                new ObjectParameter("strApellido2", strApellido2) :
                new ObjectParameter("strApellido2", typeof(string));
    
            var strCorreoParameter = strCorreo != null ?
                new ObjectParameter("strCorreo", strCorreo) :
                new ObjectParameter("strCorreo", typeof(string));
    
            var strTelefonoParameter = strTelefono != null ?
                new ObjectParameter("strTelefono", strTelefono) :
                new ObjectParameter("strTelefono", typeof(string));
    
            var strDireccionParameter = strDireccion != null ?
                new ObjectParameter("strDireccion", strDireccion) :
                new ObjectParameter("strDireccion", typeof(string));
    
            var strUsuarioParameter = strUsuario != null ?
                new ObjectParameter("strUsuario", strUsuario) :
                new ObjectParameter("strUsuario", typeof(string));
    
            var strPassParameter = strPass != null ?
                new ObjectParameter("strPass", strPass) :
                new ObjectParameter("strPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INS_RegistrarUsuario", strNombreParameter, strApellido1Parameter, strApellido2Parameter, strCorreoParameter, strTelefonoParameter, strDireccionParameter, strUsuarioParameter, strPassParameter);
        }
    
        public virtual ObjectResult<string> PA_CONS_ConsultarEmailRegistrado(string strCorreo)
        {
            var strCorreoParameter = strCorreo != null ?
                new ObjectParameter("strCorreo", strCorreo) :
                new ObjectParameter("strCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_CONS_ConsultarEmailRegistrado", strCorreoParameter);
        }
    
        public virtual int PA_CambiosPassword(string strCorreo, string strPass)
        {
            var strCorreoParameter = strCorreo != null ?
                new ObjectParameter("strCorreo", strCorreo) :
                new ObjectParameter("strCorreo", typeof(string));
    
            var strPassParameter = strPass != null ?
                new ObjectParameter("strPass", strPass) :
                new ObjectParameter("strPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_CambiosPassword", strCorreoParameter, strPassParameter);
        }
    
        public virtual int PA_INS_SolicitaCambio(string strUsuario, Nullable<int> nCambio)
        {
            var strUsuarioParameter = strUsuario != null ?
                new ObjectParameter("strUsuario", strUsuario) :
                new ObjectParameter("strUsuario", typeof(string));
    
            var nCambioParameter = nCambio.HasValue ?
                new ObjectParameter("nCambio", nCambio) :
                new ObjectParameter("nCambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INS_SolicitaCambio", strUsuarioParameter, nCambioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_Consultar_Solicita_Password(string strUsuario)
        {
            var strUsuarioParameter = strUsuario != null ?
                new ObjectParameter("strUsuario", strUsuario) :
                new ObjectParameter("strUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_Consultar_Solicita_Password", strUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarInicioSesion_Result> PA_CONS_ConsultarInicioSesion(string strUsuario)
        {
            var strUsuarioParameter = strUsuario != null ?
                new ObjectParameter("strUsuario", strUsuario) :
                new ObjectParameter("strUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarInicioSesion_Result>("PA_CONS_ConsultarInicioSesion", strUsuarioParameter);
        }
    
        public virtual int PA_Mantenimiento_PAQ_ESTADO_PEDIDO(Nullable<int> nOperacion, Nullable<bool> bNotifica, Nullable<int> nCodigo, string strDescripcion)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var bNotificaParameter = bNotifica.HasValue ?
                new ObjectParameter("bNotifica", bNotifica) :
                new ObjectParameter("bNotifica", typeof(bool));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Mantenimiento_PAQ_ESTADO_PEDIDO", nOperacionParameter, bNotificaParameter, nCodigoParameter, strDescripcionParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrases_Paginacion_Result1> PA_CONS_ConsultarFrases_Paginacion(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrases_Paginacion_Result1>("PA_CONS_ConsultarFrases_Paginacion", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosFrases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosFrases");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasesLike_Result> PA_CONS_ConsultarFrasesLike(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasesLike_Result>("PA_CONS_ConsultarFrasesLike", strNombreParameter);
        }
    
        public virtual int PA_InsertarFrases(Nullable<int> nAccion, Nullable<int> nCodigo, string strDescripcion, Nullable<bool> bInactivo, byte[] bySticker)
        {
            var nAccionParameter = nAccion.HasValue ?
                new ObjectParameter("nAccion", nAccion) :
                new ObjectParameter("nAccion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var byStickerParameter = bySticker != null ?
                new ObjectParameter("bySticker", bySticker) :
                new ObjectParameter("bySticker", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_InsertarFrases", nAccionParameter, nCodigoParameter, strDescripcionParameter, bInactivoParameter, byStickerParameter);
        }
    
        public virtual int PA_ActivarFrase(Nullable<int> nCodigo, Nullable<bool> bBool)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var bBoolParameter = bBool.HasValue ?
                new ObjectParameter("bBool", bBool) :
                new ObjectParameter("bBool", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActivarFrase", nCodigoParameter, bBoolParameter);
        }
    
        public virtual ObjectResult<byte[]> PA_CONS_ConsultarStickerxID(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("PA_CONS_ConsultarStickerxID", nCodigoParameter);
        }
    
        public virtual int PA_ActivarVinil(Nullable<int> nCodigo, Nullable<bool> bBool)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var bBoolParameter = bBool.HasValue ?
                new ObjectParameter("bBool", bBool) :
                new ObjectParameter("bBool", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActivarVinil", nCodigoParameter, bBoolParameter);
        }
    
        public virtual ObjectResult<byte[]> PA_CONS_ConsultarImgxIDVinil(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("PA_CONS_ConsultarImgxIDVinil", nCodigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosVinil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosVinil");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarVinil_Paginacion_Result> PA_CONS_ConsultarVinil_Paginacion(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarVinil_Paginacion_Result>("PA_CONS_ConsultarVinil_Paginacion", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarVinilLike_Result> PA_CONS_ConsultarVinilLike(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarVinilLike_Result>("PA_CONS_ConsultarVinilLike", strNombreParameter);
        }
    
        public virtual int PA_InsertarVinil(Nullable<int> nCodigo, string strNombre, string strDescripcion, Nullable<bool> bInactivo, byte[] byImg)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var byImgParameter = byImg != null ?
                new ObjectParameter("byImg", byImg) :
                new ObjectParameter("byImg", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_InsertarVinil", nCodigoParameter, strNombreParameter, strDescripcionParameter, bInactivoParameter, byImgParameter);
        }
    
        public virtual int PA_MantenimientoVinil(Nullable<int> nAccion, Nullable<int> nCodigo, string strNombre, string strDescripcion, Nullable<bool> bInactivo, byte[] bySticker)
        {
            var nAccionParameter = nAccion.HasValue ?
                new ObjectParameter("nAccion", nAccion) :
                new ObjectParameter("nAccion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var byStickerParameter = bySticker != null ?
                new ObjectParameter("bySticker", bySticker) :
                new ObjectParameter("bySticker", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MantenimientoVinil", nAccionParameter, nCodigoParameter, strNombreParameter, strDescripcionParameter, bInactivoParameter, byStickerParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarEstados_Result> PA_CONS_ConsultarEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarEstados_Result>("PA_CONS_ConsultarEstados");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrases_Paginacion_Sticker_Result> PA_CONS_ConsultarFrases_Paginacion_Sticker(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrases_Paginacion_Sticker_Result>("PA_CONS_ConsultarFrases_Paginacion_Sticker", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistroStickers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistroStickers");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasesLike_Sticker_Result> PA_CONS_ConsultarFrasesLike_Sticker(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasesLike_Sticker_Result>("PA_CONS_ConsultarFrasesLike_Sticker", strNombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistroVinilActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistroVinilActivo");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarVinil_Paginacion_Img_Result> PA_CONS_ConsultarVinil_Paginacion_Img(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarVinil_Paginacion_Img_Result>("PA_CONS_ConsultarVinil_Paginacion_Img", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarVinilLike_Img_Result> PA_CONS_ConsultarVinilLike_Img(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarVinilLike_Img_Result>("PA_CONS_ConsultarVinilLike_Img", strNombreParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrases_Paginacion_Usuario_Result> PA_CONS_ConsultarFrases_Paginacion_Usuario(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrases_Paginacion_Usuario_Result>("PA_CONS_ConsultarFrases_Paginacion_Usuario", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasesLike_Usuario_Result> PA_CONS_ConsultarFrasesLike_Usuario(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasesLike_Usuario_Result>("PA_CONS_ConsultarFrasesLike_Usuario", strNombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosFrases_Usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosFrases_Usuario");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasexID_Result> PA_CONS_ConsultarFrasexID(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasexID_Result>("PA_CONS_ConsultarFrasexID", nCodigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MantenimientoFrases_(Nullable<int> nAccion, Nullable<int> nCodigo, string strDescripcion, Nullable<bool> bInactivo, byte[] bySticker)
        {
            var nAccionParameter = nAccion.HasValue ?
                new ObjectParameter("nAccion", nAccion) :
                new ObjectParameter("nAccion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var byStickerParameter = bySticker != null ?
                new ObjectParameter("bySticker", bySticker) :
                new ObjectParameter("bySticker", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MantenimientoFrases_", nAccionParameter, nCodigoParameter, strDescripcionParameter, bInactivoParameter, byStickerParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPreguntas_Result> PA_CONS_ConsultarPreguntas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPreguntas_Result>("PA_CONS_ConsultarPreguntas");
        }
    
        public virtual int PA_Mantenimiento_Preguntas(Nullable<int> nOperacion, Nullable<bool> bInactivo, Nullable<int> nCodigo, string strDescripcion)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Mantenimiento_Preguntas", nOperacionParameter, bInactivoParameter, nCodigoParameter, strDescripcionParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPreguntaxID_Result> PA_CONS_ConsultarPreguntaxID(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPreguntaxID_Result>("PA_CONS_ConsultarPreguntaxID", nCodigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_Obtener_NumeroPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_Obtener_NumeroPedido");
        }
    
        public virtual ObjectResult<PA_INS_InsertarImagenPedido_Result> PA_INS_InsertarImagenPedido(Nullable<int> nCodigo, byte[] byImagen)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var byImagenParameter = byImagen != null ?
                new ObjectParameter("byImagen", byImagen) :
                new ObjectParameter("byImagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_INS_InsertarImagenPedido_Result>("PA_INS_InsertarImagenPedido", nCodigoParameter, byImagenParameter);
        }
    
        public virtual int PA_Eliminar_ImagenPedido(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Eliminar_ImagenPedido", nCodigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_INS_InsertarImagenPedidoUsuario(Nullable<int> nCodigo, byte[] byImagen)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var byImagenParameter = byImagen != null ?
                new ObjectParameter("byImagen", byImagen) :
                new ObjectParameter("byImagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_INS_InsertarImagenPedidoUsuario", nCodigoParameter, byImagenParameter);
        }
    
        public virtual int PA_INS_InsertarRespuestasUsuario(Nullable<int> nPregunta, string strRespuesta, Nullable<int> nPedido)
        {
            var nPreguntaParameter = nPregunta.HasValue ?
                new ObjectParameter("nPregunta", nPregunta) :
                new ObjectParameter("nPregunta", typeof(int));
    
            var strRespuestaParameter = strRespuesta != null ?
                new ObjectParameter("strRespuesta", strRespuesta) :
                new ObjectParameter("strRespuesta", typeof(string));
    
            var nPedidoParameter = nPedido.HasValue ?
                new ObjectParameter("nPedido", nPedido) :
                new ObjectParameter("nPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INS_InsertarRespuestasUsuario", nPreguntaParameter, strRespuestaParameter, nPedidoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPrecios_Result> PA_CONS_ConsultarPrecios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPrecios_Result>("PA_CONS_ConsultarPrecios");
        }
    
        public virtual int PA_MantenimientoPrecios(Nullable<int> nOperacion, Nullable<int> nCodigo, string strDescripcion, Nullable<decimal> nValor)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var nValorParameter = nValor.HasValue ?
                new ObjectParameter("nValor", nValor) :
                new ObjectParameter("nValor", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MantenimientoPrecios", nOperacionParameter, nCodigoParameter, strDescripcionParameter, nValorParameter);
        }
    
        public virtual int PA_ActualizarInfoUsuario(Nullable<int> nCodicion, Nullable<int> nCodigo, string strNombre, string strApellido1, string strApellido2, string strCorreo, string strTel, string strDireccion)
        {
            var nCodicionParameter = nCodicion.HasValue ?
                new ObjectParameter("nCodicion", nCodicion) :
                new ObjectParameter("nCodicion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strApellido1Parameter = strApellido1 != null ?
                new ObjectParameter("strApellido1", strApellido1) :
                new ObjectParameter("strApellido1", typeof(string));
    
            var strApellido2Parameter = strApellido2 != null ?
                new ObjectParameter("strApellido2", strApellido2) :
                new ObjectParameter("strApellido2", typeof(string));
    
            var strCorreoParameter = strCorreo != null ?
                new ObjectParameter("strCorreo", strCorreo) :
                new ObjectParameter("strCorreo", typeof(string));
    
            var strTelParameter = strTel != null ?
                new ObjectParameter("strTel", strTel) :
                new ObjectParameter("strTel", typeof(string));
    
            var strDireccionParameter = strDireccion != null ?
                new ObjectParameter("strDireccion", strDireccion) :
                new ObjectParameter("strDireccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActualizarInfoUsuario", nCodicionParameter, nCodigoParameter, strNombreParameter, strApellido1Parameter, strApellido2Parameter, strCorreoParameter, strTelParameter, strDireccionParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarUsuario_Result> PA_CONS_ConsultarUsuario(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarUsuario_Result>("PA_CONS_ConsultarUsuario", nCodigoParameter);
        }
    
        public virtual int PA_AsignarPuntos(Nullable<int> nUsuario, Nullable<int> nCantidad)
        {
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            var nCantidadParameter = nCantidad.HasValue ?
                new ObjectParameter("nCantidad", nCantidad) :
                new ObjectParameter("nCantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_AsignarPuntos", nUsuarioParameter, nCantidadParameter);
        }
    
        public virtual int PA_RegistrarPedido(Nullable<int> nCodigo, Nullable<int> nUsuario, Nullable<int> nPersonalizado, string strTipoAlbum, Nullable<int> nVinil, string strNumeroTransferencia, Nullable<decimal> nMonto, Nullable<int> nEstado, Nullable<System.DateTime> date)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            var nPersonalizadoParameter = nPersonalizado.HasValue ?
                new ObjectParameter("nPersonalizado", nPersonalizado) :
                new ObjectParameter("nPersonalizado", typeof(int));
    
            var strTipoAlbumParameter = strTipoAlbum != null ?
                new ObjectParameter("strTipoAlbum", strTipoAlbum) :
                new ObjectParameter("strTipoAlbum", typeof(string));
    
            var nVinilParameter = nVinil.HasValue ?
                new ObjectParameter("nVinil", nVinil) :
                new ObjectParameter("nVinil", typeof(int));
    
            var strNumeroTransferenciaParameter = strNumeroTransferencia != null ?
                new ObjectParameter("strNumeroTransferencia", strNumeroTransferencia) :
                new ObjectParameter("strNumeroTransferencia", typeof(string));
    
            var nMontoParameter = nMonto.HasValue ?
                new ObjectParameter("nMonto", nMonto) :
                new ObjectParameter("nMonto", typeof(decimal));
    
            var nEstadoParameter = nEstado.HasValue ?
                new ObjectParameter("nEstado", nEstado) :
                new ObjectParameter("nEstado", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_RegistrarPedido", nCodigoParameter, nUsuarioParameter, nPersonalizadoParameter, strTipoAlbumParameter, nVinilParameter, strNumeroTransferenciaParameter, nMontoParameter, nEstadoParameter, dateParameter);
        }
    
        public virtual int PA_ActivarCategoria(Nullable<int> nCodigo, Nullable<bool> bBool)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var bBoolParameter = bBool.HasValue ?
                new ObjectParameter("bBool", bBool) :
                new ObjectParameter("bBool", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActivarCategoria", nCodigoParameter, bBoolParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCategoria_Paginacion_Result> PA_CONS_ConsultarCategoria_Paginacion(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCategoria_Paginacion_Result>("PA_CONS_ConsultarCategoria_Paginacion", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCategoriaLike_Result> PA_CONS_ConsultarCategoriaLike(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCategoriaLike_Result>("PA_CONS_ConsultarCategoriaLike", strNombreParameter);
        }
    
        public virtual ObjectResult<byte[]> PA_CONS_ConsultarImgxIDCategoria(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("PA_CONS_ConsultarImgxIDCategoria", nCodigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosCategoria");
        }
    
        public virtual int PA_MantenimientoCategoria(Nullable<int> nAccion, Nullable<int> nCodigo, string strNombre, string strDescripcion, Nullable<bool> bInactivo, byte[] bySticker)
        {
            var nAccionParameter = nAccion.HasValue ?
                new ObjectParameter("nAccion", nAccion) :
                new ObjectParameter("nAccion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            var bInactivoParameter = bInactivo.HasValue ?
                new ObjectParameter("bInactivo", bInactivo) :
                new ObjectParameter("bInactivo", typeof(bool));
    
            var byStickerParameter = bySticker != null ?
                new ObjectParameter("bySticker", bySticker) :
                new ObjectParameter("bySticker", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MantenimientoCategoria", nAccionParameter, nCodigoParameter, strNombreParameter, strDescripcionParameter, bInactivoParameter, byStickerParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MantenimientoAlbumPredefinido(Nullable<int> nOperacion, Nullable<int> nCodigo, string strNombre, Nullable<int> nCategoria)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var nCategoriaParameter = nCategoria.HasValue ?
                new ObjectParameter("nCategoria", nCategoria) :
                new ObjectParameter("nCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MantenimientoAlbumPredefinido", nOperacionParameter, nCodigoParameter, strNombreParameter, nCategoriaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MantenimientoImgAlbumPredefinido(Nullable<int> nOperacion, Nullable<int> nAlbum, Nullable<int> nCodigo, byte[] byImg, Nullable<bool> bPortada)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var nAlbumParameter = nAlbum.HasValue ?
                new ObjectParameter("nAlbum", nAlbum) :
                new ObjectParameter("nAlbum", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var byImgParameter = byImg != null ?
                new ObjectParameter("byImg", byImg) :
                new ObjectParameter("byImg", typeof(byte[]));
    
            var bPortadaParameter = bPortada.HasValue ?
                new ObjectParameter("bPortada", bPortada) :
                new ObjectParameter("bPortada", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MantenimientoImgAlbumPredefinido", nOperacionParameter, nAlbumParameter, nCodigoParameter, byImgParameter, bPortadaParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCategoria_Result> PA_CONS_ConsultarCategoria(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCategoria_Result>("PA_CONS_ConsultarCategoria", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarAlbum_Paginacion_Result> PA_CONS_ConsultarAlbum_Paginacion(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarAlbum_Paginacion_Result>("PA_CONS_ConsultarAlbum_Paginacion", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarAlbum_Paginacion__Result> PA_CONS_ConsultarAlbum_Paginacion_(Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarAlbum_Paginacion__Result>("PA_CONS_ConsultarAlbum_Paginacion_", nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarAlbumLike_Result> PA_CONS_ConsultarAlbumLike(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarAlbumLike_Result>("PA_CONS_ConsultarAlbumLike", strNombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosAlbum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosAlbum");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarImagenesAlbumPredefinido_V2_Result> PA_CONS_ConsultarImagenesAlbumPredefinido_V2(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarImagenesAlbumPredefinido_V2_Result>("PA_CONS_ConsultarImagenesAlbumPredefinido_V2", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCategoriaImgs_Result> PA_CONS_ConsultarCategoriaImgs(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCategoriaImgs_Result>("PA_CONS_ConsultarCategoriaImgs", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarAlbumxCategoria_Result> PA_CONS_ConsultarAlbumxCategoria(Nullable<int> nCategoria)
        {
            var nCategoriaParameter = nCategoria.HasValue ?
                new ObjectParameter("nCategoria", nCategoria) :
                new ObjectParameter("nCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarAlbumxCategoria_Result>("PA_CONS_ConsultarAlbumxCategoria", nCategoriaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarPuntosxUsuario(Nullable<int> nUsuario)
        {
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarPuntosxUsuario", nUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPedidos_Paginados_Result> PA_CONS_ConsultarPedidos_Paginados(Nullable<int> nCodigo, Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPedidos_Paginados_Result>("PA_CONS_ConsultarPedidos_Paginados", nCodigoParameter, nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPedidos_Paginados_v2_Result> PA_CONS_ConsultarPedidos_Paginados_v2(Nullable<int> nCodigo, Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPedidos_Paginados_v2_Result>("PA_CONS_ConsultarPedidos_Paginados_v2", nCodigoParameter, nPaginaParameter, nDatosParameter);
        }
    
        public virtual int PA_RegistrarPedido_V2(Nullable<int> nCodigo, Nullable<int> nUsuario, Nullable<int> nPersonalizado, string strTipoAlbum, Nullable<int> nVinil, string strNumeroTransferencia, Nullable<decimal> nMonto, Nullable<int> nEstado, Nullable<System.DateTime> date)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            var nPersonalizadoParameter = nPersonalizado.HasValue ?
                new ObjectParameter("nPersonalizado", nPersonalizado) :
                new ObjectParameter("nPersonalizado", typeof(int));
    
            var strTipoAlbumParameter = strTipoAlbum != null ?
                new ObjectParameter("strTipoAlbum", strTipoAlbum) :
                new ObjectParameter("strTipoAlbum", typeof(string));
    
            var nVinilParameter = nVinil.HasValue ?
                new ObjectParameter("nVinil", nVinil) :
                new ObjectParameter("nVinil", typeof(int));
    
            var strNumeroTransferenciaParameter = strNumeroTransferencia != null ?
                new ObjectParameter("strNumeroTransferencia", strNumeroTransferencia) :
                new ObjectParameter("strNumeroTransferencia", typeof(string));
    
            var nMontoParameter = nMonto.HasValue ?
                new ObjectParameter("nMonto", nMonto) :
                new ObjectParameter("nMonto", typeof(decimal));
    
            var nEstadoParameter = nEstado.HasValue ?
                new ObjectParameter("nEstado", nEstado) :
                new ObjectParameter("nEstado", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_RegistrarPedido_V2", nCodigoParameter, nUsuarioParameter, nPersonalizadoParameter, strTipoAlbumParameter, nVinilParameter, strNumeroTransferenciaParameter, nMontoParameter, nEstadoParameter, dateParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPedidos_Paginados_v3_Result> PA_CONS_ConsultarPedidos_Paginados_v3(Nullable<int> nCodigo, Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPedidos_Paginados_v3_Result>("PA_CONS_ConsultarPedidos_Paginados_v3", nCodigoParameter, nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarRegistrosPedido(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarRegistrosPedido", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPedidos_Paginados_v4_Result> PA_CONS_ConsultarPedidos_Paginados_v4(Nullable<int> nCodigo, Nullable<int> nPagina, Nullable<int> nDatos)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var nPaginaParameter = nPagina.HasValue ?
                new ObjectParameter("nPagina", nPagina) :
                new ObjectParameter("nPagina", typeof(int));
    
            var nDatosParameter = nDatos.HasValue ?
                new ObjectParameter("nDatos", nDatos) :
                new ObjectParameter("nDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPedidos_Paginados_v4_Result>("PA_CONS_ConsultarPedidos_Paginados_v4", nCodigoParameter, nPaginaParameter, nDatosParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarPedidoxId_Result> PA_CONS_ConsultarPedidoxId(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarPedidoxId_Result>("PA_CONS_ConsultarPedidoxId", nCodigoParameter);
        }
    
        public virtual ObjectResult<byte[]> PA_CONS_ConsultarFotosxPedido(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("PA_CONS_ConsultarFotosxPedido", nCodigoParameter);
        }
    
        public virtual ObjectResult<string> PA_CONS_ConsultarFrasesxPedido(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_CONS_ConsultarFrasesxPedido", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarRespuestasxPedido_Result> PA_CONS_ConsultarRespuestasxPedido(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarRespuestasxPedido_Result>("PA_CONS_ConsultarRespuestasxPedido", nCodigoParameter);
        }
    
        public virtual int PA_InsertarFrasesxPedido(Nullable<int> nPedido, Nullable<int> nFrase)
        {
            var nPedidoParameter = nPedido.HasValue ?
                new ObjectParameter("nPedido", nPedido) :
                new ObjectParameter("nPedido", typeof(int));
    
            var nFraseParameter = nFrase.HasValue ?
                new ObjectParameter("nFrase", nFrase) :
                new ObjectParameter("nFrase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_InsertarFrasesxPedido", nPedidoParameter, nFraseParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFotosxPedido__Result> PA_CONS_ConsultarFotosxPedido_(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFotosxPedido__Result>("PA_CONS_ConsultarFotosxPedido_", nCodigoParameter);
        }
    
        public virtual int PA_ActualizarEstadoPedido(Nullable<int> nPedido, Nullable<int> nEstado)
        {
            var nPedidoParameter = nPedido.HasValue ?
                new ObjectParameter("nPedido", nPedido) :
                new ObjectParameter("nPedido", typeof(int));
    
            var nEstadoParameter = nEstado.HasValue ?
                new ObjectParameter("nEstado", nEstado) :
                new ObjectParameter("nEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActualizarEstadoPedido", nPedidoParameter, nEstadoParameter);
        }
    
        public virtual int PA_Actualizar_Parametro(Nullable<int> nCodigo, string strDescripcion)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strDescripcionParameter = strDescripcion != null ?
                new ObjectParameter("strDescripcion", strDescripcion) :
                new ObjectParameter("strDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Parametro", nCodigoParameter, strDescripcionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_ConsultarCantidadProyectos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_ConsultarCantidadProyectos");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarColor_Result> PA_CONS_ConsultarColor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarColor_Result>("PA_CONS_ConsultarColor");
        }
    
        public virtual ObjectResult<byte[]> PA_CONS_ConsultarImgxProyecto(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("PA_CONS_ConsultarImgxProyecto", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_ConsultarParametros_Result> PA_ConsultarParametros(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_ConsultarParametros_Result>("PA_ConsultarParametros", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_ConsultarProyecto_Result> PA_ConsultarProyecto(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_ConsultarProyecto_Result>("PA_ConsultarProyecto", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_ConsultarProyectoImg_Result> PA_ConsultarProyectoImg(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_ConsultarProyectoImg_Result>("PA_ConsultarProyectoImg", nCodigoParameter);
        }
    
        public virtual int PA_MantenimientoProyecto(Nullable<int> nOperacion, Nullable<int> nCodigo, string strNombre, string strCategoria, byte[] byImg)
        {
            var nOperacionParameter = nOperacion.HasValue ?
                new ObjectParameter("nOperacion", nOperacion) :
                new ObjectParameter("nOperacion", typeof(int));
    
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strCategoriaParameter = strCategoria != null ?
                new ObjectParameter("strCategoria", strCategoria) :
                new ObjectParameter("strCategoria", typeof(string));
    
            var byImgParameter = byImg != null ?
                new ObjectParameter("byImg", byImg) :
                new ObjectParameter("byImg", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MantenimientoProyecto", nOperacionParameter, nCodigoParameter, strNombreParameter, strCategoriaParameter, byImgParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarUsuarioAdmin_Result> PA_CONS_ConsultarUsuarioAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarUsuarioAdmin_Result>("PA_CONS_ConsultarUsuarioAdmin");
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarEstadoxId_Result> PA_CONS_ConsultarEstadoxId(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarEstadoxId_Result>("PA_CONS_ConsultarEstadoxId", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasesLike_V2_Result> PA_CONS_ConsultarFrasesLike_V2(string strNombre)
        {
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasesLike_V2_Result>("PA_CONS_ConsultarFrasesLike_V2", strNombreParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarFrasesxPedido_V2_Result> PA_CONS_ConsultarFrasesxPedido_V2(Nullable<int> nCodigo)
        {
            var nCodigoParameter = nCodigo.HasValue ?
                new ObjectParameter("nCodigo", nCodigo) :
                new ObjectParameter("nCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarFrasesxPedido_V2_Result>("PA_CONS_ConsultarFrasesxPedido_V2", nCodigoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarTelMemories_Result> PA_CONS_ConsultarTelMemories(Nullable<int> nTel)
        {
            var nTelParameter = nTel.HasValue ?
                new ObjectParameter("nTel", nTel) :
                new ObjectParameter("nTel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarTelMemories_Result>("PA_CONS_ConsultarTelMemories", nTelParameter);
        }
    
        public virtual int PA_EliminarPuntos(Nullable<int> nUsuario)
        {
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_EliminarPuntos", nUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCorreo_Result> PA_CONS_ConsultarCorreo(Nullable<int> nCorreo)
        {
            var nCorreoParameter = nCorreo.HasValue ?
                new ObjectParameter("nCorreo", nCorreo) :
                new ObjectParameter("nCorreo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCorreo_Result>("PA_CONS_ConsultarCorreo", nCorreoParameter);
        }
    
        public virtual ObjectResult<PA_CONS_ConsultarCuentaBancaria_Result> PA_CONS_ConsultarCuentaBancaria(Nullable<int> nCuenta)
        {
            var nCuentaParameter = nCuenta.HasValue ?
                new ObjectParameter("nCuenta", nCuenta) :
                new ObjectParameter("nCuenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_ConsultarCuentaBancaria_Result>("PA_CONS_ConsultarCuentaBancaria", nCuentaParameter);
        }
    
        public virtual int PA_EliminarPuntos_Cantidad(Nullable<int> nUsuario, Nullable<int> nCantidad)
        {
            var nUsuarioParameter = nUsuario.HasValue ?
                new ObjectParameter("nUsuario", nUsuario) :
                new ObjectParameter("nUsuario", typeof(int));
    
            var nCantidadParameter = nCantidad.HasValue ?
                new ObjectParameter("nCantidad", nCantidad) :
                new ObjectParameter("nCantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_EliminarPuntos_Cantidad", nUsuarioParameter, nCantidadParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_CONS_CantidadImgsxPedido(Nullable<int> nId)
        {
            var nIdParameter = nId.HasValue ?
                new ObjectParameter("nId", nId) :
                new ObjectParameter("nId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_CONS_CantidadImgsxPedido", nIdParameter);
        }
    
        public virtual int PA_InsertarBitacora(string error, Nullable<System.DateTime> fecha, Nullable<int> usuario)
        {
            var errorParameter = error != null ?
                new ObjectParameter("error", error) :
                new ObjectParameter("error", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_InsertarBitacora", errorParameter, fechaParameter, usuarioParameter);
        }
    }
}
